# yazi.toml
[manager]
show_hidden = true
sort_sensitive = false
sort_dir_first = true
show_symlink = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*",   block = true, for = "windows" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

